package com.avisora.model;
// Generated 11-dic-2017 15:54:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion  implements java.io.Serializable {


     private String idOpcion;
     private Opcion opcion;
     private String desOpcion;
     private String lnkOpcion;
     private Integer ctrMenus;
     private Set opcions = new HashSet(0);
     private Set opcionUsuarios = new HashSet(0);

    public Opcion() {
    }

	
    public Opcion(String idOpcion, String desOpcion, String lnkOpcion) {
        this.idOpcion = idOpcion;
        this.desOpcion = desOpcion;
        this.lnkOpcion = lnkOpcion;
    }
    public Opcion(String idOpcion, Opcion opcion, String desOpcion, String lnkOpcion, Integer ctrMenus, Set opcions, Set opcionUsuarios) {
       this.idOpcion = idOpcion;
       this.opcion = opcion;
       this.desOpcion = desOpcion;
       this.lnkOpcion = lnkOpcion;
       this.ctrMenus = ctrMenus;
       this.opcions = opcions;
       this.opcionUsuarios = opcionUsuarios;
    }
   
    public String getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(String idOpcion) {
        this.idOpcion = idOpcion;
    }
    public Opcion getOpcion() {
        return this.opcion;
    }
    
    public void setOpcion(Opcion opcion) {
        this.opcion = opcion;
    }
    public String getDesOpcion() {
        return this.desOpcion;
    }
    
    public void setDesOpcion(String desOpcion) {
        this.desOpcion = desOpcion;
    }
    public String getLnkOpcion() {
        return this.lnkOpcion;
    }
    
    public void setLnkOpcion(String lnkOpcion) {
        this.lnkOpcion = lnkOpcion;
    }
    public Integer getCtrMenus() {
        return this.ctrMenus;
    }
    
    public void setCtrMenus(Integer ctrMenus) {
        this.ctrMenus = ctrMenus;
    }
    public Set getOpcions() {
        return this.opcions;
    }
    
    public void setOpcions(Set opcions) {
        this.opcions = opcions;
    }
    public Set getOpcionUsuarios() {
        return this.opcionUsuarios;
    }
    
    public void setOpcionUsuarios(Set opcionUsuarios) {
        this.opcionUsuarios = opcionUsuarios;
    }




}


